use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use tempfile::NamedTempFile;

use crate::paths::AppPaths;
use crate::{Error, Result};

const MARKER: &str = "Generated by transfigure. Do not edit.";

pub fn ensure_available(paths: &AppPaths, name: &str) -> Result<()> {
    let path = launcher_path(paths, name);
    if path.exists() && !is_managed(&path)? {
        return Err(Error::Message(format!(
            "{} already exists and is not managed by Transfigure",
            path.display()
        )));
    }
    Ok(())
}

pub fn sync(paths: &AppPaths, name: &str) -> Result<()> {
    paths.ensure_directories()?;
    ensure_available(paths, name)?;
    let executable = env::current_exe().map_err(|source| {
        Error::Message(format!(
            "could not locate the Transfigure executable: {source}"
        ))
    })?;
    let path = launcher_path(paths, name);
    let contents = launcher_contents(&executable, name)?;
    let mut temporary = NamedTempFile::new_in(&paths.bin_dir).map_err(|source| Error::Write {
        path: paths.bin_dir.clone(),
        source,
    })?;
    temporary
        .write_all(contents.as_bytes())
        .map_err(|source| Error::Write {
            path: path.clone(),
            source,
        })?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        temporary
            .as_file()
            .set_permissions(fs::Permissions::from_mode(0o755))
            .map_err(|source| Error::Write {
                path: path.clone(),
                source,
            })?;
    }

    temporary.persist(&path).map_err(|error| Error::Write {
        path,
        source: error.error,
    })?;
    Ok(())
}

pub fn remove(paths: &AppPaths, name: &str) -> Result<()> {
    let path = launcher_path(paths, name);
    if !path.exists() {
        return Ok(());
    }
    if !is_managed(&path)? {
        return Err(Error::Message(format!(
            "refusing to remove unmanaged file {}",
            path.display()
        )));
    }
    fs::remove_file(&path).map_err(|source| Error::Write { path, source })
}

pub fn launcher_path(paths: &AppPaths, name: &str) -> PathBuf {
    #[cfg(windows)]
    {
        paths.bin_dir.join(format!("{name}.cmd"))
    }
    #[cfg(not(windows))]
    {
        paths.bin_dir.join(name)
    }
}

fn is_managed(path: &Path) -> Result<bool> {
    let contents = fs::read_to_string(path).map_err(|source| Error::Read {
        path: path.to_owned(),
        source,
    })?;
    Ok(contents.lines().take(2).any(|line| line.contains(MARKER)))
}

#[cfg(windows)]
fn launcher_contents(executable: &Path, name: &str) -> Result<String> {
    let executable = executable.to_string_lossy();
    if executable.contains(['"', '%', '\r', '\n']) {
        return Err(Error::Message(
            "the Transfigure executable path contains characters unsupported by Windows launchers"
                .into(),
        ));
    }
    Ok(format!(
        "@echo off\r\nrem {MARKER}\r\n\"{executable}\" __run \"{name}\" %*\r\n"
    ))
}

#[cfg(not(windows))]
fn launcher_contents(executable: &Path, name: &str) -> Result<String> {
    let executable = executable
        .to_str()
        .ok_or_else(|| Error::Message("the executable path is not valid UTF-8".into()))?;
    Ok(format!(
        "#!/bin/sh\n# {MARKER}\nexec {} __run {} \"$@\"\n",
        shell_quote(executable),
        shell_quote(name)
    ))
}

#[cfg(not(windows))]
fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn launcher_has_management_marker() {
        let contents = launcher_contents(Path::new("/tmp/transfigure"), "download").unwrap();
        assert!(contents.contains(MARKER));
        assert!(contents.contains("__run"));
    }
}
